INSERT INTO AUDIOTRACK.TRACKS (ID, TRACK_TITLE, TRACK_AUTHOR, TRACK_PLAY) VALUES ('1', 'First Book', 'First Author', '30000');
INSERT INTO AUDIOTRACK.TRACKS (ID, TRACK_TITLE, TRACK_AUTHOR, TRACK_PLAY) VALUES ('2', 'Second Book', 'Second Author', '20000');
INSERT INTO AUDIOTRACK.TRACKS (ID, TRACK_TITLE, TRACK_AUTHOR, TRACK_PLAY) VALUES ('3', 'Third Book', 'Third Author', '15000');
